/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package laurencewarne.mcbiomemapserver;

import java.io.IOException;

import org.takes.http.Exit;

import laurencewarne.mcbiomemapserver.server.McBiomeMapServerInitializer;

public class App {

    // Pass minecraft install directory in cmdline args
    public static void main(String[] args) {
	final String mcInstallLocation = (args.length > 0)? args[0] :
	    System.getProperty("user.home") + "/.minecraft";
	try {
	    new McBiomeMapServerInitializer()
		.initServer(mcInstallLocation)
		.start(Exit.NEVER);;
	} catch (IOException e) {
	    e.printStackTrace();
	}
    }
}
